/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;
import Protocolo.Protocolo;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author guillermo y nacho
 */
public class VentanaConversacionSala extends javax.swing.JFrame {

    String login;
    String sala;
    Cliente cliente;
    public String respuesta;
    
    public VentanaConversacionSala(String usuario, String nombreSala, Cliente c) {
        initComponents();
        login = usuario;
        sala = nombreSala;
        cliente= c;
        labelSala.setText(sala);
        //Si el usuario cierra al ventana el servidor le saca del mapa de la sala en la que está
        this.addWindowListener(new WindowAdapter() {
        @Override
        public void windowClosing(WindowEvent evt) {
            onExit();
        }
  });
    }
    
    public void onExit() {
        String mensaje = Protocolo.mensajeSalirSala(login,sala);
        cliente.out.println(mensaje);
        this.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        campoTextoEnviado = new javax.swing.JTextArea();
        campoTextoEnviar = new javax.swing.JTextField();
        botonEnviar = new javax.swing.JButton();
        labelSala = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        campoTextoEnviado.setEditable(false);
        campoTextoEnviado.setColumns(20);
        campoTextoEnviado.setRows(5);
        jScrollPane1.setViewportView(campoTextoEnviado);

        botonEnviar.setText("Enviar");
        botonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnviarActionPerformed(evt);
            }
        });

        labelSala.setText("Sala");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoTextoEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelSala, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(labelSala)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTextoEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEnviar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void pegarTexto(String texto) {
        campoTextoEnviado.append(texto);
    }
    
    private void botonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnviarActionPerformed
        
        String texto = campoTextoEnviar.getText();
        String mensaje = Protocolo.mensajeConversacionSala(login, sala, texto);
        
        if (mensaje.split("/").length == 4) {
            cliente.out.println(mensaje);
        }
        campoTextoEnviar.setText("");
        
    }//GEN-LAST:event_botonEnviarActionPerformed

    private void windowClosed(WindowEvent e) {
        //Mensaje sacar de sala
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEnviar;
    private javax.swing.JTextArea campoTextoEnviado;
    private javax.swing.JTextField campoTextoEnviar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelSala;
    // End of variables declaration//GEN-END:variables
}
