/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;
import java.io.PrintWriter;
import Protocolo.Protocolo;

/**
 *
 * @author guillermo y nacho
 */
public class VentanaPeticionConversacion extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPeticionConversacion
     */
    String usuarioOrigen;
    String usuarioDestino;
    Cliente cliente;
    HebraRecibirMensajes hebra;
    public static int idConversacion=0;
    
    public VentanaPeticionConversacion(String origen, String destino, Cliente c, HebraRecibirMensajes hebra_) {
        initComponents();
        cliente = c;
        usuarioOrigen = origen;
        usuarioDestino = destino;
        this.textoPeticion.setText("Petición de conversación de " + origen + " a " + destino);
        hebra = hebra_;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoPeticion = new javax.swing.JLabel();
        BotonAceptarConversacion = new javax.swing.JButton();
        BotonRechazarConversacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        BotonAceptarConversacion.setText("Aceptar");
        BotonAceptarConversacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAceptarConversacionActionPerformed(evt);
            }
        });

        BotonRechazarConversacion.setText("Rechazar");
        BotonRechazarConversacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRechazarConversacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(textoPeticion, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(BotonAceptarConversacion, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(BotonRechazarConversacion, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoPeticion, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAceptarConversacion)
                    .addComponent(BotonRechazarConversacion))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAceptarConversacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAceptarConversacionActionPerformed
        
        Conversacion conv = new Conversacion(new VentanaConversacion(usuarioDestino, usuarioOrigen, cliente));
        
        hebra.conversaciones.put(usuarioDestino+usuarioOrigen, conv);
//        hebra.vConversacion = new VentanaConversacion(usuarioDestino, usuarioOrigen, cliente);
//        hebra.vConversacion.setVisible(true);
        conv.vConversacion.setVisible(true);
                
        String mensaje = Protocolo.mensajeConversacionAceptada(usuarioOrigen, usuarioDestino);
        
        System.out.println(mensaje);
        cliente.out.println(mensaje);
        this.setVisible(false);
        
    }//GEN-LAST:event_BotonAceptarConversacionActionPerformed

    private void BotonRechazarConversacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRechazarConversacionActionPerformed
        String mensaje = Protocolo.mensajeConversacionRechazada(usuarioOrigen, usuarioDestino);
        cliente.out.println(mensaje);
        this.setVisible(false);
        System.out.println("Has rechazado la peticion de " + usuarioOrigen);
    }//GEN-LAST:event_BotonRechazarConversacionActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAceptarConversacion;
    private javax.swing.JButton BotonRechazarConversacion;
    private javax.swing.JLabel textoPeticion;
    // End of variables declaration//GEN-END:variables
}
